services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: schedule_messages
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: front
    depends_on:
      - back
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "82:80"
    restart: always

  back:
    image: node:20
    container_name: back
    working_dir: /app/back
    volumes:
      - ./.env:/app/back/.env
      - ./package.json:/app/back/package.json
      - ./package-lock.json:/app/back/package-lock.json
      - ./src/models:/app/back/models
      - ./src/functions:/app/back/functions
      - ./src/services:/app/back/services
      - node_modules:/app/back/node_modules  # Volume nomeado para persistir node_modules
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=3306
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    command: sh -c "npm install && npm install pm2@latest -g && pm2 start --time ./services/api/index.js --name ScheculeMessages -- --color && pm2 logs"
    networks:
      - app_network

volumes:
  mysql_data:
  node_modules:

networks:
  app_network:
    driver: bridge